language: cpp

stages:
  - build
  - deploy
jobs:
  include:
  - stage: build
    os: linux
    script:
      - "echo Building Linux"
  - os: osx
    script:
      - "echo Building osx"
   - stage: deploy   
    script:
      - "echo deploying"