language: cpp

jobs:
  include:
  - stage: build
    os: linux
    script: "echo Building Linux"
  - stage: build        
    os: osx
    script: "echo Building osx"
  
  - stage: Deploy      
    script: "echo Deploying"