language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake 
            - g++-5
            - mesa-common-dev
            - g++-multilib
            - g++-5-multilib
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"
script:
  - "./Travis/build.sh"