language: cpp

jobs:
  include:
  - stage: build
    os: osx
    osx_image: xcode10.1
    script:
      - "./Travis/build-osx.sh"
  - stage: build        
    os: linux
    dist: trusty
    script: "echo Building Linux"
  
  - stage: Deploy      
    script: "echo Deploying"