language: cpp
matrix:
  include:
    - os: windows
      env:
      - LABEL="windows-msvc"
      - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
      script:
      - export PATH=$MSBUILD_PATH:$PATH
      - ./Travis/build-windows.bat

before_install:
    - eval "${MATRIX_EVAL}"
script:
  - "./Travis/build.sh"