language: cpp

# Build only pull requests or tags
if: tag IS present OR type IN (pull_request) OR branch =~ /^ci-.*$/

notifications:
  email: false

env:
  global:
  - HOMEBREW_NO_AUTO_UPDATE=1
  
  - APPVEYOR_ACCOUNT=JanC
  - APPVEYOR_PROJECT=xplaneconnect

  - AWS_BUCKET_NAME=aeronavmap
  - AWS_SYNC_FOLDER=$TRAVIS_BUILD_NUMBER

jobs:
  include:
  - stage: build
    os: windows
    env:
      - LABEL="windows-msvc"
      - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
    script:
      - export PATH=$MSBUILD_PATH:$PATH
      - ./Travis/build-windows.bat
