language: cpp
matrix:
  include:
    # - os: osx
    #   osx_image: xcode10.1
    - os: linux
      dist: trusty
      addons:
        apt:
        packages:
          - cmake 
          - g++-5
          - mesa-common-dev
          - g++-multilib
          - g++-5-multilib
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

# os:
#   # - osx
#   - linux

script:
  - "./Travis/build.sh"