language: cpp
matrix:
  include:
    - os: windows
      env:
      - LABEL="windows-msvc"
      - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
      install:
        - choco install windows-sdk-10-version-1809-all
      script:
      - export PATH=$MSBUILD_PATH:$PATH
      - MSBuild.exe xpcPlugin/xpcPlugin/xpcPlugin.sln
