# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- ms-azure

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'macosx10.14'
    configuration: 'Release'
    xcWorkspacePath: 'xpcPlugin/xpcPlugin.xcodeproj'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'xpc-osx-64.xpl'
    targetPath: 'xpcPlugin/XPlaneConnect/xpc-osx-64.xpl'


# pool:
#   vmImage: 'windows-latest'

# variables:
#   solution: 'xpcPlugin/xpcPlugin/xpcPlugin.sln'
#   buildPlatform: 'Win32|x64'
#   buildConfiguration: 'Release'
#   appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

# steps:
# - task: NuGetToolInstaller@0

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     platform: 'Win32'
#     solution: '$(solution)'
#     configuration: '$(buildConfiguration)'
#     msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
