# Get the base Ubuntu image from Docker Hub
FROM ubuntu:16.04
 
# Update apps on the base image
RUN apt-get -y update && apt-get install -y
 
# Install the Clang compiler
RUN apt-get -y install cmake g++ mesa-common-dev g++-multilib
 
# Copy the current folder which contains C++ source code to the Docker image under /usr/src
COPY xpcPlugin /usr/src/xpcPlugin
 
# Specify the working directory
WORKDIR /usr/src/xpcPlugin
 
# Use Clang to compile the Test.cpp source file
RUN cmake .
RUN make
 
